### ISSUE TITLE
sveltekit-theme-switch.mdx uses the deprecate __layout.svelte file

### ISSUE THREAD

**Issue by jastuccio** [nico-bachner/v5#1]
Hello Nico,

Thanks for the blog post explaining how you created your ThemeSwitcher!  I am referencing several posts and Youtube videos to create a ThemeSwitcher component of my own.

One thing I noticed is you are using `__layout.svelte` which means this for beta SvelteKit not the SvelteKit 1.0 version?  I am unsure if anything else would need to be changed besides using `+layout.svelte` so I am opening an issue instead of making a pull request.

I'm will probably use the html data-theme attribute for the switcher.  
🙂

**Comment by nico-bachner** [comment]
Thanks for the feedback!

I'm glad to hear my post has been of use to you.

You are indeed correct that at the time of writing, 1.0 had not been released yet. Well spotted! I have updated the layout file name to match the new naming convention.

If you're using the a data-theme attribute, don't forget to still include the meta tag (see https://github.com/whatwg/html/issues/4504 for more info)

```html
<meta name="color-scheme" content="light dark" />
```
